apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-db-secret
  namespace: demo
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: web-db-secret
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: RDS_MASTER_SECRET_ARN_PLACEHOLDER
        property: host
    - secretKey: port
      remoteRef:
        key: RDS_MASTER_SECRET_ARN_PLACEHOLDER
        property: port
    - secretKey: database
      remoteRef:
        key: RDS_MASTER_SECRET_ARN_PLACEHOLDER
        property: dbname
    - secretKey: username
      remoteRef:
        key: RDS_MASTER_SECRET_ARN_PLACEHOLDER
        property: username
    - secretKey: password
      remoteRef:
        key: RDS_MASTER_SECRET_ARN_PLACEHOLDER
        property: password
