apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - secret-store.yaml
  - external-secret.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: rds-managed-secret-ref
    literals:
      - secretArn=arn:aws:secretsmanager:ap-southeast-1:193229476041:secret:rds!db-ff48c4ab-6e6a-47a7-9ea3-6ab72c77511d-RoSv6u
replacements:
  - source:
      kind: ConfigMap
      name: rds-managed-secret-ref
      fieldPath: data.secretArn
    targets:
      - select:
          kind: ExternalSecret
          name: web-db-secret
        fieldPaths:
          - spec.data.[secretKey=host].remoteRef.key
          - spec.data.[secretKey=port].remoteRef.key
          - spec.data.[secretKey=database].remoteRef.key
          - spec.data.[secretKey=username].remoteRef.key
          - spec.data.[secretKey=password].remoteRef.key
