apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/open-policy-agent/gatekeeper-library//library/general/disallowedtags?ref=master
  - https://github.com/open-policy-agent/gatekeeper-library//library/general/containerresources?ref=master
  - https://github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/users?ref=master
  - https://github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/host-network-ports?ref=master
  - templates/max-deployment-replicas-template.yaml
  - constraints/disallow-latest-tag.yaml
  - constraints/require-limits.yaml
  - constraints/disallow-root-user.yaml
  - constraints/disallow-hostnetwork.yaml
  - constraints/max-deployment-replicas.yaml
