apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/disallow-latest-tag-template.yaml
  - templates/required-limits-template.yaml
  - templates/disallow-root-user-template.yaml
  - templates/disallow-hostnetwork-template.yaml
  - templates/max-deployment-replicas-template.yaml
  - constraints/disallow-latest-tag.yaml
  - constraints/require-limits.yaml
  - constraints/disallow-root-user.yaml
  - constraints/disallow-hostnetwork.yaml
  - constraints/max-deployment-replicas.yaml
