apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demo
  name: viewer-binding
  labels:
    app.kubernetes.io/part-of: p2-w10-lab
    app.kubernetes.io/managed-by: argocd
subjects:
  - kind: ServiceAccount
    name: viewer-sa
    namespace: demo
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
