apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: demo
  labels:
    app.kubernetes.io/part-of: p2-w10-lab
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-sa
  namespace: demo
  labels:
    app.kubernetes.io/part-of: p2-w10-lab
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-sa
  namespace: demo
  labels:
    app.kubernetes.io/part-of: p2-w10-lab
    app.kubernetes.io/managed-by: argocd
