apiVersion: v1
kind: LimitRange
metadata:
  name: payments-defaults
  namespace: payments
  labels:
    app.kubernetes.io/part-of: p2-w10-lab
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 128Mi
      max:
        cpu: "2"
        memory: 2Gi
