apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: p2-w10-lab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/component: stable
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
