apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: w10-lab
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.6.0
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        replicaCount: 1
        webhook:
          replicaCount: 1
        certController:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: externalsecrets.external-secrets.io
      managedFieldsManagers:
        - kube-apiserver
        - argocd-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
