apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - rbac.yaml
  - gatekeeper.yaml
  - monitoring.yaml
  - argo-rollouts.yaml
  - external-secrets.yaml
  - external-secrets-rds.yaml
  - sigstore-policy-controller.yaml
  - sigstore-policies.yaml
  - payments.yaml
  - web.yaml
  - web-monitoring.yaml
  - gatekeeper-policies.yaml
  - payments-app.yaml
