apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/part-of: p2-w10-lab
    app.kubernetes.io/managed-by: argocd
