apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: w10-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: AppProject for the w10-lab GitOps demo.
  sourceRepos:
    - https://github.com/pho-veteran/w10-gitops.git
    - https://github.com/argoproj/argo-rollouts.git
    - https://prometheus-community.github.io/helm-charts
    - https://open-policy-agent.github.io/gatekeeper/charts
    - https://charts.external-secrets.io
    - https://sigstore.github.io/helm-charts
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc
    - namespace: gatekeeper-system
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: cosign-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
