apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base
images:
- name: w10-web
  newName: vihn/w10-web
  newTag: main-412ff42
labels:
- pairs:
    app.kubernetes.io/environment: lab
