apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8smaxdeploymentreplicas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: K8sMaxDeploymentReplicas
      validation:
        openAPIV3Schema:
          type: object
          properties:
            max:
              type: integer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8smaxdeploymentreplicas

        violation[{"msg": msg}] {
          replicas := input.review.object.spec.replicas
          max := input.parameters.max
          replicas > max
          msg := sprintf("Deployment <%v> has %v replicas; maximum allowed is %v", [input.review.object.metadata.name, replicas, max])
        }
